version: "3.7"

services:
  service1:
    build: service1
    restart: always
    ports:
      - 6060:80
    volumes: 
      - mydata:/code/container_data

  service2:
    build: service2
    restart: always
    ports:
      - 7070:80

volumes:
  mydata:
