version: "3"

services:

  service1:
    build: service1
    restart: always
    ports:
      - 7000:80
    volumes: 
      - ./service1/mydata:/code/container_data

  service2:
    build: service2
    restart: always
    ports:
      - 8000:80

# volumes:
#   mydata:

# add comment for new branch
